server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/mini_api_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: hiling11
  #配置rabbitMq 服务器
  rabbitmq:
    host: 172.16.164.2
    port: 5672
    username: hiling
    password: 123456
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 商品服务
  try-host: http://127.0.0.1:${server.port}